apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: setup-operator
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
# - apiGroups:
#   - ""
#   resources:
#   - pods
#   - nodes
#   - services
#   - endpoints
#   - persistentvolume
#   - persistentvolumeclaims
  
#   - events
#   - configmaps
#   - secrets
#   verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# - apiGroups:
#   - apps
#   resources:
#   - deployments
#   - daemonsets
#   - replicasets
#   - statefulsets
#   verbs:
#   - "*"
# - apiGroups:
#   - monitoring.coreos.com
#   resources:
#   - servicemonitors
#   verbs:
#   - '*'
# - apiGroups:
#   - app.example.com
#   resources:
#   - '*'
#   verbs:
#   - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: setup-operator
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
