apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: podsets.app.example.com
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.sshKeyPath
    name: Default
    type: string
  - JSONPath: .status.sshKeyPath
    name: Current
    type: string
  - JSONPath: .spec.sshPrivateKey
    name: Default
    type: string
  - JSONPath: .status.sshPrivateKey
    name: Current
    type: string
  - JSONPath: .spec.sshPublicKey
    name: Default
    type: string
  - JSONPath: .status.sshPublicKey
    name: Current
    type: string
  group: app.example.com
  names:
    kind: PodSet
    listKind: PodSetList
    plural: podsets
    singular: podset
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: PodSetSpec defines the ssh key path of PodSet
          properties:
            sshKeyPath:
              format: string
              type: string
            sshPublicKey:
              format: string
              type: string
            sshPrivateKey:
              format: string
              type: string
          required:
          - sshKeyPath
          - sshPrivateKey
          type: object
        status:
          description: PodSetStatus defines the observed state of PodSet
          properties:
            podNames:
              items:
                type: string
              type: array
            sshKeyPath:
              format: string
              type: string
            sshPublicKey:
              format: string
              type: string
            sshPrivateKey:
              format: string
              type: string
          required:
          - podNames
          - sshKeyPath
          - sshPublicKey
          - sshPrivateKey
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
